config/routes.rb
MyNagios::Engine.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  root 'welcome#index'
  match 'autorefresh',    to: 'welcome#autorefresh',    via: [:post]
  match 'group_action',   to: 'checks#group_action',    via: [:post]

  resources :checks do
    member do
      post :run_now
      post :toggle
    end
  end
end

app/models/my_nagios/check.rb
module MyNagios
  class Check < ActiveRecord::Base
    belongs_to :group

    enum status:  [ :info, :success, :critical ]
    enum state:   [ :completed, :running ]

    scope :enabled,     -> { where(enabled: true) }
    scope :not_snoozed, -> { where('`my_nagios_checks`.`snooze_for` <= UTC_TIMESTAMP() OR `my_nagios_checks`.`snooze_for` IS NULL') }

    attr_accessor :additional_command_result

    INFO_STATES  = ['AuthenticationFailed message', 'No such file or directory']
    ERROR_STATES = ['!ruby/exception', 'packet_write_wait: Connection to UNKNOWN: Broken pipe']

    def run!
      begin
        self.update(state: :running)

        Net::SSH.start( self.host, self.user, MyNagios::Check.ssh_config(self.pem_key) ) do |ssh|
          result = ssh.exec! self.command
          status = self.determinate_status_by_response(result)

          self.additional_command_result = ssh.exec!(self.additional_command) if not self.additional_command.blank? and status.eql?(:critical)

          self.update(state: :completed, status: status, latest_state: result, latest_updated_at: Time.now)
        end
      rescue => e
        self.update(state: :completed, status: :info, latest_state: e, latest_updated_at: Time.now)
      end
    end

    def self.multiple_run!(check_ids, config)
      check_list = MyNagios::Check.where(id: check_ids)

      begin
        check_list.update_all(state: :running)

        Net::SSH.start( config['host'], config['user'], MyNagios::Check.ssh_config(config['pem_key']) ) do |ssh|
          check_list.each do |check|
            result = ssh.exec! check.command
            status = check.determinate_status_by_response(result)

            check.additional_command_result = ssh.exec!(check.additional_command) if not check.additional_command.blank? and status.eql?(:critical)

            check.update(state: :completed, status: status, latest_state: result, latest_updated_at: Time.now)
          end
        end

      rescue => e
        check_list.each { |check| check.update(state: :completed, status: :info, latest_state: e, latest_updated_at: Time.now) }
      end
    end

    def determinate_status_by_response(response)
      return :critical if not regexp.blank? and response =~ /#{regexp}/
      return :critical if not response.scan('CRITICAL').blank?
      return :info     if response.nil? or MyNagios::Check::INFO_STATES.any? { |msg| response.include?(msg) }
      :success
    end

    def self.ssh_config(pem_key = nil)
      config = { config: true, non_interactive: true, auth_methods: ['publickey', 'hostbased'] }
      config[:keys] = [pem_key] unless pem_key.blank?

      config
    end

  end
end

app/models/my_nagios/group.rb
module MyNagios
  class Group < ActiveRecord::Base
    has_many :checks
  end
end

app/controllers/my_nagios/application_controller.rb
module MyNagios
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/my_nagios/checks_controller.rb
require_dependency "my_nagios/application_controller"

module MyNagios
  class ChecksController < ApplicationController
    before_filter :find_check,  only: [:run_now, :toggle, :edit, :update]
    before_filter :find_groups, only: [:new, :create, :edit]

    def new
      @check = Check.new
    end

    def create
      @check = Check.create(params_check)
      redirect_to root_path
    end

    def edit
    end

    def update
      @check.update(params_check)
      redirect_to root_path
    end

    def run_now
      @check.run!

      respond_to do |format|
        format.js { render layout: false }
      end
    end

    def toggle
      @check.toggle! :enabled

      respond_to do |format|
        format.js { render layout: false }
      end
    end

    def group_action
      check_ids = params["group_action_check_ids"].split(',')
      redirect_to root_path and return if check_ids.blank?

      case params['check_group_action'].downcase
      when 'disable'
        Check.where(id: check_ids).update_all(enabled: false)
      when 'enable'
        Check.where(id: check_ids).update_all(enabled: true)
      when 'snooze for'
        Check.where(id: check_ids).update_all(snooze_for: (Time.now + params['snooze_time_select'].to_i.minutes))
      end

      redirect_to root_path
    end

    private

    def find_check
      @check = Check.find(params[:id])
    end

    def find_groups
      @groups = MyNagios::Group.all
    end

    def params_check
      params.require(:check).permit(:host, :user, :pem_key, :description, :interval, :command, :additional_command, :regexp, :group_id)
    end
  end
end

app/controllers/my_nagios/welcome_controller.rb
require_dependency "my_nagios/application_controller"

module MyNagios
  class WelcomeController < ApplicationController

    skip_before_action :verify_authenticity_token, only: [:autorefresh]
    before_filter :find_criticals, only: [:index, :autorefresh]

    def index
      @group = Group.all.includes(:checks)
    end

    def autorefresh
      respond_to do |format|
        format.js { render layout: false }
      end
    end

    private

    def find_criticals
      @criticals = Check.enabled.where(status: Check.statuses[:critical])
    end

  end
end

app/helpers/my_nagios/application_helper.rb
module MyNagios
  module ApplicationHelper
  end
end

app/helpers/my_nagios/checks_helper.rb
module MyNagios
  module ChecksHelper

    def human_time(time)
      return '-' unless time

      distance_of_time_in_words(time, Time.now) + ' ago'
    end

    def status_to_label(status)
      return 'danger' if status.eql?('critical')

      status
    end

  end
end

app/helpers/my_nagios/welcome_helper.rb
module MyNagios
  module WelcomeHelper
  end
end

app/views/layouts/my_nagios/application.haml
!!! 5
%html
  %head
    %title MyNagios
    = stylesheet_link_tag 'my_nagios/application', media: 'all'
    = javascript_include_tag 'my_nagios/application'
    = csrf_meta_tag

  %body.container-fluid
    #my_nagios_body
      = yield

app/views/my_nagios/checks/_check_row.haml
- run_now     ||= false
- show_group  ||= false
- is_snooze     = check.snooze_for && (check.snooze_for.utc > Time.now.utc)

- tr_id = show_group ? nil : dom_id(check)
- tr_html_class  = check.enabled? ? 'enabled' : 'disabled'
- tr_html_class += ' alert alert-info' if is_snooze

- td_html_class = is_snooze ? 'snooze_for' : ''

%tr{ id: tr_id, class: tr_html_class }
  - if show_group
    %td
      =link_to check.group.name, "##{dom_id(check)}", class: 'fail_check'
  - else
    %td
      =check.command
      ="(regexp: #{check.regexp})" unless check.regexp.blank?
      %p.check_interval= "run every: #{check.interval} min"

  %td{ class: td_html_class }
    %span.label{ class: "label-#{status_to_label(check.status)}"}= check.status
    =check.latest_state

    - if is_snooze
      %div.snooze_for
        Snooze for: #{check.snooze_for}

    - if show_group
      %strong=check.command

  %td=human_time(check.latest_updated_at)

  - if run_now
    %td
      #check_now
        =link_to 'run now', run_now_check_path(check), class: 'check_now', method: :post, remote: true
        =image_tag 'my_nagios/chasing_arrows.gif', class: 'spinner'
      #actions
        %br
        =link_to 'edit', edit_check_path(check)
        =link_to (check.enabled? ? 'disable' : 'enable' ), toggle_check_path(check), class: 'disable_check', method: :post, data: { remote: true, confirm: 'Are you sure?' }

    %td
      .checkbox_holder.my_nagios_check
        =check_box_tag dom_id(check, :checkbox), nil, false, data: { check_id: check.id }, class: "group_#{check.group_id}"

app/views/my_nagios/checks/_form.haml
.row.col-sm-12
  =form_for @check, html: { class: 'form-horizontal' } do |f|

    .form-group
      =f.label :group_id, class: 'col-sm-1 control-label'
      .col-sm-10
        =f.select :group_id, options_for_select( @groups.map{|g| [g.name, g.id]}, @check.group_id ), class: 'form-control'

    .form-group
      =f.label :host, class: 'col-sm-1 control-label'
      .col-sm-10
        =f.text_field :host, class: 'form-control'

    .form-group
      =f.label :user, class: 'col-sm-1 control-label'
      .col-sm-10
        =f.text_field :user, class: 'form-control'

    .form-group
      =f.label :pem_key, class: 'col-sm-1 control-label'
      .col-sm-10
        =f.text_field :pem_key, class: 'form-control'

    .form-group
      =f.label :description, class: 'col-sm-1 control-label'
      .col-sm-10
        =f.text_field :description, class: 'form-control'

    .form-group
      =f.label :interval, class: 'col-sm-1 control-label'
      .col-sm-10
        =f.text_field :interval, class: 'form-control'

    .form-group
      =f.label :command, class: 'col-sm-1 control-label'
      .col-sm-10
        =f.text_field :command, class: 'form-control'

    .form-group
      =f.label :additional_command, 'Additional command (runs if command is fail)', class: 'col-sm-1 control-label'
      .col-sm-10
        =f.text_field :additional_command, class: 'form-control'

    .form-group
      =f.label :regexp, 'Critical if match:', class: 'col-sm-1 control-label'
      .col-sm-10
        =f.text_field :regexp, class: 'form-control'

    .form-group
      .col-sm-10.col-sm-offset-1
        =f.submit

    .form-group
      .col-sm-10.col-sm-offset-1
        delete

app/views/my_nagios/checks/edit.haml
%h2 Edit check
%hr

= render partial: 'form'

app/views/my_nagios/checks/new.haml
%h2 Add new check
%hr

= render partial: 'form'

app/views/my_nagios/checks/run_now.js.erb
tr = '<%= dom_id(@check) %>'
$(tr).replaceWith('<%= j render(partial: '/my_nagios/checks/check_row', locals: { check: @check }) %>')

tr = '<%= dom_id(@check) %>'
$(tr).find('img.spinner').hide()

$(tr).find('a.check_now').click (event) ->
  onclick_check_now(event)

onclick_check_now = (event) ->
  $(event.target).closest('tr').addClass('updating')
  $(event.target).closest('tr').find('img.spinner').show()

app/views/my_nagios/welcome/_failures_list.haml
#failures_list
  .timer
  %h3 Critical errors:

  - if @criticals.blank?
    %p No criticals
  - else

    %table.table.failures_list
      %colgroup
        %col{ width: '10%'}
        %col{ width: '80%'}
        %col{ width: '5%'}
        %col{ width: '5%'}
        - criticals.each do |check|
          = render partial: '/my_nagios/checks/check_row', locals: { check: check, show_group: true }

app/views/my_nagios/welcome/index.haml
=link_to  'Add new check', new_check_path

= render partial: 'failures_list', locals: { criticals: @criticals, show_group: true }

#group_action.text-center.alert.alert-warning{ role: :alert }
  =form_tag group_action_path do
    Please, set action for selected checks:
    =select_tag :check_group_action, options_for_select(['Disable', 'Enable', 'Snooze for'])
    =select_tag :snooze_time_select, options_for_select(['15 min', '30 min', '60 min'])
    =hidden_field_tag :group_action_check_ids
    =submit_tag



#checks{ data: :no_turbolink }
  %table.table.check_list
    %colgroup
      %col{ width: '10%'}
      %col{ width: '78%'}
      %col{ width: '5%'}
      %col{ width: '5%'}
      %col{ width: '2%'}
    %tr
      %td
      %td
      %td
      %td
      %td
        .checkbox_holder
          =check_box_tag :select_all

    - @group.each do |group|
      %tr
        %td{ colspan: 2 }
          %h3=group.name
        %td
          %h4 Last run:
        %td
          %h4 Actions:
        %td
          .checkbox_holder
            =check_box_tag "select_all_group_#{group.id}", nil, false, class: 'select_all_group', data: { select_all_group: group.id}

      - group.checks.each do |check|
        = render partial: '/my_nagios/checks/check_row', locals: { check: check, run_now: true }